### ISSUE TITLE
Issues launchin Playnite 4k on 1440p screen

### ISSUE THREAD

**Issue by Supergamer1337** [lyckantropen/moonlight_hdr_launcher#7]
I've tried to start Playnite (in 4k) on my 1440p HDR display using Moonlight Launcher. However, when I try to do so it constantly tries to switch between 1440p resolution and 4k. As is evident by this log file:
[moonlight_hdr_launcher_log.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/6693093/moonlight_hdr_launcher_log.txt)

These are the settings used:
[gamestream_playnite.ini.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/6693097/gamestream_playnite.ini.txt)
[moonlight_hdr_launcher.ini.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/6693098/moonlight_hdr_launcher.ini.txt)

_`.txt` at the end is because Github does not support `.ini`_

Is this because of some intended behaviour or just a bug?

**Comment by lyckantropen** [comment]
I think this is an issue with gamestream launcher. You should try and reproduce it without MHL and file an issue there.

**Comment by ReenigneCA** [comment]
I think this should be closed. 

Gamestream launchpad uses standard windows apis to change the resolution of the desktop and assumes that you set a resolution that works. It also sits in the background to verify the resolution doesn't get changed and then changes back to it or at least tries every 2 seconds. This is intended to clean up after games that modify the resolution and don't change it back when you return to a launcher like PlayNite or steam.  I'm actually curious if there is any flicker or anything when you say it switches back and forth between 4k and 1440p. 4k actually is a supported resolution for gamestream so you shouldn't have to use gamestream launchpad or any other tool to force it and I believe it should just work. Gamestream is doing special magic driver stuff after all, it just refuses to do that to enable hdr if your monitor isn't hdr.

As to what's happening for you my best guess is that gamestream is setting the 4k resolution you ask for then gamestream is trying to set 4k but failing and maybe falling back to 1440p then it checks to see what resolution it is and sees it isn't 4k and then tries again and again and again every 2 seconds. Personally I prefer the higher refresh rates at 1440p to 4k resolution that actually takes some work to get done seamlessly as gamestream supports 1080p and 4k but not 1440p and so that's when you need an intermediary like gamestream launchpad (or if my latest pull request is accepted moonlight_hdr_launchpad with some new ini options,) to make things work seamlessly.
